### ISSUE TITLE
`from` and `to` are used in incorrect order?

### ISSUE THREAD

**Issue by safareli** [purescript/purescript-either#26]
`toEither3 :: Either3 Number Number Number -> Color` should be named `fromEither3`  as it takes Either3 (it's not returning Either3).

`fromEither3 :: Color -> Either3 Number Number Number` returns Either and it should be named `toEither3`.

Am I messing something?

```purescript
data Color = Red Number | Green Number | Blue Number
-- 
toEither3 :: Either3 Number Number Number -> Color
toEither3 = either3 Red Green Blue

fromEither3 :: Color -> Either3 Number Number Number
fromEither3 (Red   v) = in1 v
fromEither3 (Green v) = in2 v
fromEither3 (Blue  v) = in3 v
```
[see](https://github.com/purescript/purescript-either/blob/6ce722db809cd3f8476c4a41fb0de3a2630fe802/src/Data/Either/Nested.purs#L9-L17)

**Comment by garyb** [comment]
Hah yes, you're quite right!
