### ISSUE TITLE
Add Left and Right projections into some Alternative

### ISSUE THREAD

**Issue by safareli** [purescript/purescript-either#31]
I think it might be useful to have functions like this:

```purescript
asRight :: forall e a f. Alternative f => Either e a -> f a
asRight (Right x) = pure x
asRight _ = empty

asLeft :: forall e a f. Alternative f => Either e a -> f e
asLeft (Left x) = pure x
asLeft _ = empty
```

let me know if this is desired addition and will open PR. (are names fine?)

**Comment by paf31** [comment]
I think these are short enough (`either pure (const empty)`) that they don't need to be separate named functions.
