### ISSUE TITLE
`fromLeft` / `fromRight` shouldn't be partial

### ISSUE THREAD

**Issue by kritzcreek** [purescript/purescript-either#47]
I'd like to have

```purescript
fromLeft :: forall a b. a -> Either a b -> a
fromRight ::  forall a b. b -> Either a b -> b
```
over the current partial

```purescript
fromLeft :: Partial => forall a b. Either a b -> a
fromLeft :: Partial => forall a b. Either a b -> b
```

as typing `either (const a) identity` becomes old rather quickly and I need these functions much more frequently than their partial counterparts. I'm not sure how confusing it would be to define these functions differently in two modules in this package, but even if don't rename the old ones I think this would be a win.

**Comment by JordanMartinez** [comment]
Agreed, and shouldn't the current `fromLeft` be `unsafeFromLeft`?

If the current type signature is swapped out for your type signature, how will this affect the results one sees when one searches for `fromLeft` via Pursuit? Will both versions of the same function appear?

**Comment by hdgarrood** [comment]
Pursuit only includes the latest version of each library in the search index, so only the new version would show up.

**Comment by hdgarrood** [comment]
I’d advocate dropping the partial variant actually: you can easily recover it with `fromLeft (crashWith “whatever”)`

**Comment by hdgarrood** [comment]
I think it is a little unfortunate that doing this would introduce an inconsistency with maybe though, as fromJust is partial. It also departs from Haskell as well right?

**Comment by hdgarrood** [comment]
On reflection I’m a little less enthusiastic about this, given how low down in the ecosystem it is.

**Comment by JordanMartinez** [comment]
> I think it is a little unfortunate that doing this would introduce an inconsistency with maybe though, as fromJust is partial.

That's what I thought after reading your comment.

What if the function was called something other than `fromLeft`? For example 
`eitherL default (\leftValue -> body) either` 
and the same for `eitherR`?

**Comment by hdgarrood** [comment]
fromLeftWithDefault maybe?

**Comment by JordanMartinez** [comment]
I feel like that name is too long. What about `eitherLeft` and `eitherRight`?

**Comment by hdgarrood** [comment]
Abbreviations are overrated imo, especially in cases like this where the function we are considering doesn’t have an existing agreed-upon name. We also have editor tooling to reduce the burden of typing it out. I’m not keen on eitherLeft.

**Comment by JordanMartinez** [comment]
Hard to argue with those points, haha. I've been on the side where a terse function name left me confused about it for quite a while...

**Comment by kRITZCREEK** [comment]
> doesn’t have an existing agreed-upon name

`base` has them fwiw: http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Either.html#v:fromLeft

**Comment by hdgarrood** [comment]
Oh! I wasn’t aware of that, that does change things actually. I’ll withdraw my objection then.

**Comment by JordanMartinez** [comment]
To help with migration, should there be a `fromLeft'` and vice versa for those who still want the Partial version of this function?

**Comment by hdgarrood** [comment]
I’d suggest not, unless we intend to keep them in the library. Updating `fromLeft` to `fromLeft’` is, in practice, going to be pretty much equally arduous as updating it to `fromLeft (crashWith “unexpected Right”)`, because the time consuming part is finding the files you need to change and checking that stuff still compiles after making the changes.

**Comment by garyb** [comment]
We could restore the `Unsafe` module like we had pre-`Partial` and move the `Partial` versions in there.

I don't see this PR getting merged until we have another reason to break the whole ecosystem (like a breaking compiler release), just so you know @JordanMartinez.

**Comment by JordanMartinez** [comment]
> I don't see the PR getting merged until we have another reason to break the whole ecosystem (like a breaking compiler release)

Ok. Thanks for the heads up. 

> We could restore the `Unsafe` module like we had pre-`Partial` and move the `Partial` versions in there.

In my PR, should I also add the `Unsafe` module? If so, what should the functions be called?

**Comment by safareli** [comment]
would like to know what you think on somewhat related topic https://github.com/purescript/purescript-maybe/issues/44
