### ISSUE TITLE
Consider Unsafe or Partial for `from*`

### ISSUE THREAD

**Issue by toastal** [purescript/purescript-either#56]
A recent version of `Data.Either` moved `fromRight` and `fromLeft` to no longer be be partial but to provide a default. Perhaps these should be a `Data.Either.Partial.from*` version as can be seen with: https://github.com/purescript/purescript-strings/pull/128

**Comment by garyb** [comment]
The better option now is to use `either (unsafeCrashWith "...") identity`, where `...` is some kind of explanation of what it is or why it went wrong.

We could perhaps add them back under an `Either.Unsafe` module, but I think it would be better if they included a string still, so there's some clue to what went wrong in the inconceivable case that they do actually fail. :wink:

**Comment by hdgarrood** [comment]
I would prefer not to re-add them; I don’t think they’re useful often enough to justify a spot here, especially since writing `fromRight (crashWith "...")` is only one more function application.

**Comment by toastal** [comment]
That's a smart option too! I wasn't sure the correct route would be. But I can update the `strings` lib once the message is settled.

**Comment by natefaubion** [comment]
> The better option now is to use either (unsafeCrashWith "...") identity, where ... is some kind of explanation of what it is or why it went wrong.

Let’s not forget which language we are programming in 😅 😜

**Comment by hdgarrood** [comment]
Oh, haha, oops. So I guess we'd need to do something like `either (\_ -> unsafeCrashWith "...") identity`. The total version of `fromRight` is not suitable for this at all then, I guess you'd have to do something like `(_ $ unit) <<< fromRight (\_ -> unsafeCrashWith "..") <<< map const`.

Maybe we want lazy versions of the form `fromRight' :: forall a b. (Unit -> b) -> Either a b -> b`?

**Comment by garyb** [comment]
Ah yeah, I used `either` exactly so it could be `(\_ -> ....)` in that branch, rather than suggesting `fromRight (crashWith ...`. But yeah, adding the lazy `fromLeft` / `fromRight` would also work and perhaps be worthwhile.

**Comment by toastal** [comment]
Assuming this is a common thing (which wouldn't surprise me given that it's in the library already), what should the message say? `"Invalid RegExp: \`string_here\`"`?

**Comment by hdgarrood** [comment]
We should probably reuse the error from the Left constructor, so actually I suppose `either unsafeCrashWith identity` should work.

**Comment by toastal** [comment]
Seems reasonabele. I'll have a look after my shower.

**Comment by JordanMartinez** [comment]
Since Maybe has a lazy version of `fromMaybe`: [fromMaybe'](https://pursuit.purescript.org/packages/purescript-maybe/4.0.1/docs/Data.Maybe#v:fromMaybe'), should this library have the same for `fromLeft` and `fromRight`, too?

**Comment by kl0tl** [comment]
Should we consider an `unsafeFromRight :: Either String a -> a` function as an alias for `either unsafeCrashWith identity`?

Otherwise is there anything left to do now that we have `fromLeft' :: forall a b. (Unit -> a) -> Either a b -> a` and  `fromRight' :: forall a b. (Unit -> b) -> Either a b -> b` or can we close this issue?

**Comment by hdgarrood** [comment]
I think I would prefer to close the issue; the `fromLeft'` and `fromRight'` functions definitely ought to help fill this gap, and more API surface is a liability. I think arguably we shouldn't be encouraging use of unsafe functions by making them too comfortable to reach; that's a principle we've followed in the core libraries fairly consistently.

**Comment by JordanMartinez** [comment]
I'm in favor of closing this, too.
